### ISSUE TITLE
the datatset

### ISSUE THREAD

**Issue by Mrlong12** [jiwei0921/SOD-CNNs-based-code-summary-#1]
Do  you have  the 3D dataset(STEREO)?

**Comment by jiwei0921** [comment]
Yes, I do. The download link is 
https://pan.baidu.com/s/1cEaHYaNzTAFBsKIB28FHdA

**Comment by Mrlong12** [comment]
Thank you very much!

**Comment by Mrlong12** [comment]
Do you have the origin size image dataset? the link dataset image size is 256*256

**Comment by lartpang** [comment]
RGBD的可以看这篇文章使用的数据：https://github.com/JXingZhao/ContrastPrior

**Comment by Mrlong12** [comment]
OK，thanks
