### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by Mrlong12** [jiwei0921/SOD-CNNs-based-code-summary-#2]
请问一下max-F，F-measure,mean F-measure，这三个显著性评价指标有什么区别？

**Comment by lartpang** [comment]
一般是使用maxF，meanF，MAE。

这里的maxF与meanF计算公式，都是在计算Fmeasure一样，但是对应的二值图不同。这两个指标使用了Precision和Recall两个量，二者是需要二值图的，但是显著性的预测结果类似于一个概率图。0～1。

maxF使用的是0～1之间动态阈值，一般是255个均匀阈值划分，分别计算最终的二值图对应的Fmeasure，选择得分最大的最为maxF。meanF使用的是显著性图的均值的二倍作为阈值。大于1的时候使用1代替。来计算Fmeasure。

可以使用这个 仓库来评估：https://github.com/ArcherFMY/sal_eval_toolbox

**Comment by Mrlong12** [comment]
十分感谢您的解答，那么如果我的maxF低，meanF高所代表的意义是什么呢？

**Comment by lartpang** [comment]
一般情况下，maxF要比meanF要高，因为他是一个动态选择的过程，实际上包含了meanF的情况。

因为他是指标，对应的结果越好，也就代表算法的效果不错。当然，也只能说不错，并不完全代表视觉效果很好。

**Comment by Mrlong12** [comment]
十分感谢您的回答，我是想问如果我做对比实验的时候与别人对比，我的maxF低但是meanF高说明什么？

**Comment by lartpang** [comment]
确实存在这样的情况，只能说明模型设计上确实有些不足，所以有些方法只会比较maxF，或者只会比较meanF。

**Comment by Mrlong12** [comment]
请问我最近看到一篇论文他的评价指标是F-measure，我看我的maxF比他的F-measure好，meanF比他的Fmeasure差，能说我比他好吗？

**Comment by lartpang** [comment]
一般而言，最好是都高些，mae也要低些，但是如果你的模型创新性很强的话，稍微有些不足也是OK的。

**Comment by Mrlong12** [comment]
不是，我的意思是他论文用的指标是F-measure，但是我不知道他算的是meanF，还是maxF。他没做说明，我不知道拿meanF和他的F-meansure比还是maxF和他的F-measure比

**Comment by lartpang** [comment]
@Mrlong12 你可以参照最新的显著性检测的论文，看下你这篇文章结果的大致水平，进而可以比较出是平均还是最大。

**Comment by Patrickctyyx** [comment]
> 不是，我的意思是他论文用的指标是F-measure，但是我不知道他算的是meanF，还是maxF。他没做说明，我不知道拿meanF和他的F-meansure比还是maxF和他的F-measure比

如果他的方法提供了显著图，那你就拿他的显著图在你的指标下面测一下结果就行，最好不要直接拿别人论文的结果进行对比
