### ISSUE TITLE
关于DUT数据集结果的问题

### ISSUE THREAD

**Issue by zyrant** [jiwei0921/SOD-CNNs-based-code-summary-#6]
jiwei，您好
       首先感谢你们辛苦制作的DUT数据集。
       我发现在你们在DMRA这篇文章中的DUT数据集的结果（比如DMRA,CPFP等）是采用DUT单独训练得到的，而在20年和21年的其他文章中都采用NJU2K+NLPR+DUT（比如：CONet，SSF等）一起训练得到的DUT的结果。
       我想请教您，请问通过不同训练集分法得到DUT结果一起对比是否公平（如20年，21的文章）？这两种分法得到的DUT数据集的结果是很接近吗？

zy

**Comment by jiwei0921** [comment]
感谢您的关注。

准确的来说，目前的工作通常采用两种训练设置分别测试DUT和其他benchmark数据集的结果。两种训练设置下的模型测试结果肯定是有差异的，主要原因是不同数据集的domain shift，例如DUT的数据集捕获均在生活场景，包含很多低光、低对比度环境。而NJUD则包含了一些Internet的图片。

您可以参考我们最新的论文(Calibrated RGB-D Salient Object Detection, CVPR21), 或者 (Uncertainty Inspired RGB-D Saliency Detection, IEEE TPAMI21) 去公平地比较目前的方法。训练集的划分，可以参考 https://github.com/jiwei0921/RGBD-SOD-datasets 。
