### ISSUE TITLE
how to read it?

### ISSUE THREAD

**Issue by javatoai** [jiwei0921/SOD-CNNs-based-code-summary-#9]
我有一些问题，想请教一下：
1. 我想读2d的文章， 我该怎么读呢？
2. 只用读2021年最新的文章就可以了吗， 以前的比如2016-2020年发表的论文还用读吗？
3. 读的时候我应该注意那些地方呢？
4. 读的时候，需要额外关注代码吗？
5. 论文名字上带红旗图标代表是什么意思呢？

**Comment by jiwei0921** [comment]
1-2. 可以从20年到21年去读这些文章，等这些文章读完，基本上你也会了解整个领域，然后在粗读早起的文章，去梳理发展的脉络。
3. 这个可以参考知乎一些，如果高效阅读文章的blog，会有较深的感悟。
4. 我个人的建议，可以从最新工作中选取几个较有代表性的，去复现和使用。
5. 意味着它是这个领域最新出现的文章。
